name: Newman Run ServerRest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do seu repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o Node.js (v20 é a recomendada atualmente)
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Instala o Newman e o Reporter
      - name: Instalar Newman e htmlextra
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # 4. Cria a pasta para os artefatos (opcional, o newman cria sozinho)
      - name: Criar diretório de resultados
        run: mkdir -p newman

      # 5. Executa os testes
      # Importante: O caminho dos arquivos .json deve estar correto na raiz do seu repo
      - name: Executar Testes da API
        run: |
          newman run ServerRest.postman_collection.json \
          -e serveRest_env.postman_environment.json \
          -r htmlextra \
          --reporter-htmlextra-export newman/report.html
    
      # 6. Faz o upload do relatório HTML para o GitHub
      - name: Publicar Relatório
        if: always() # Garante que o relatório seja gerado mesmo se os testes falharem
        uses: actions/upload-artifact@v4
        with:
          name: Relatorios-Newman
          path: newman/
        
          
